load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "slowlog",
    srcs = [
        "aggregator.go",
        "normalizer.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/util/slowlog",
    visibility = ["//visibility:public"],
)

go_test(
    name = "slowlog_test",
    timeout = "short",
    srcs = [
        "aggregator_test.go",
        "normalizer_test.go",
    ],
    embed = [":slowlog"],
    flaky = False,
    deps = [
        "@com_github_stretchr_testify//require",
    ],
)
