load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "plancache",
    srcs = [
        "warmup.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/plancache",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config",
        "//pkg/kv",
        "//pkg/metrics",
        "//pkg/sessionctx",
        "//pkg/util",
        "//pkg/util/chunk",
        "//pkg/util/logutil",
        "@com_github_pingcap_errors//:errors",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "plancache_test",
    timeout = "short",
    srcs = ["warmup_test.go"],
    embed = [":plancache"],
    flaky = False,
    deps = [
        "//pkg/config",
        "//pkg/parser/ast",
        "//pkg/parser/mysql",
        "//pkg/planner/core/resolve",
        "//pkg/sessionctx",
        "//pkg/types",
        "//pkg/util",
        "//pkg/util/chunk",
        "//pkg/util/sqlexec",
        "@com_github_ngaut_pools//:pools",
        "@com_github_pingcap_errors//:errors",
        "@com_github_stretchr_testify//require",
    ],
)
